spring.application.name=unimarket-usuarios
management.metrics.tags.application=${spring.application.name}

# Observability (Metrics & Tracing)
management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
